comment: false

ignore:
  - "R/plots.R"
  - "R/utils.R"
  - "R/compute_ci.R"

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
